/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package diazadvjavaproject3;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Locale;
import javax.swing.JOptionPane;

/**
 *
 * @author Dave
 */
public class GUI extends javax.swing.JFrame {
    // Private Date member
    private Date date;
    // The arraylist of StoreItems for the item inventory.
    ArrayList<StoreItem> itemInventory = new ArrayList<StoreItem>();
    public GUI() 
    {
        initComponents();
        txtWidth.setEnabled(false);
        txtHeight.setEnabled(false);
        txtMedia.setEnabled(false);
        
        txtActor1.setEnabled(false);
        txtActor2.setEnabled(false);
        txtActress1.setEnabled(false);
        txtActress2.setEnabled(false);
        txtDirector.setEnabled(false);
        
        txtGenre.setEnabled(false);
        
        btnAdd.setEnabled(false);
        btnSell.setEnabled(false);
        
        panelB.setEnabled(true);
        panelC.setEnabled(false);
        panelD.setEnabled(false);
        panelE.setEnabled(false);
        panelF.setEnabled(false);
        panelG.setEnabled(false);
        
        lblRecords.setEnabled(false);
        lblProfit.setEnabled(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupButton = new javax.swing.ButtonGroup();
        panelA = new javax.swing.JPanel();
        radPainting = new javax.swing.JRadioButton();
        radMovie = new javax.swing.JRadioButton();
        radBook = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        panelB = new javax.swing.JPanel();
        txtSellingPrice = new javax.swing.JTextField();
        txtTitle = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtPurchasePrice = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtAuthor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        panelC = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtActor1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtActress2 = new javax.swing.JTextField();
        txtDirector = new javax.swing.JTextField();
        txtActor2 = new javax.swing.JTextField();
        txtActress1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        panelD = new javax.swing.JPanel();
        txtGenre = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        panelE = new javax.swing.JPanel();
        txtWidth = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtMedia = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtHeight = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtOutput = new javax.swing.JTextArea();
        panelF = new javax.swing.JPanel();
        lblRecords = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        lblProfit = new javax.swing.JLabel();
        panelG = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnSell = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(800, 775));

        panelA.setToolTipText("");

        groupButton.add(radPainting);
        radPainting.setText("Painting");
        radPainting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radPaintingActionPerformed(evt);
            }
        });

        groupButton.add(radMovie);
        radMovie.setText("Movie");
        radMovie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radMovieActionPerformed(evt);
            }
        });

        groupButton.add(radBook);
        radBook.setText("Book");
        radBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radBookActionPerformed(evt);
            }
        });

        jLabel1.setText("Select Category:");

        javax.swing.GroupLayout panelALayout = new javax.swing.GroupLayout(panelA);
        panelA.setLayout(panelALayout);
        panelALayout.setHorizontalGroup(
            panelALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelALayout.createSequentialGroup()
                .addGroup(panelALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelALayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(radBook)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radMovie, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radPainting))
                    .addComponent(jLabel1))
                .addContainerGap())
        );
        panelALayout.setVerticalGroup(
            panelALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelALayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radBook)
                    .addComponent(radPainting)
                    .addComponent(radMovie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel7.setText("Date: DD/MM/YY");

        jLabel3.setText("Title:");

        jLabel6.setText("Selling Price:");

        jLabel4.setText("Author:");

        jLabel2.setText("Fill Out:");

        jLabel5.setText("Purchase Price:");

        javax.swing.GroupLayout panelBLayout = new javax.swing.GroupLayout(panelB);
        panelB.setLayout(panelBLayout);
        panelBLayout.setHorizontalGroup(
            panelBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(panelBLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPurchasePrice, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSellingPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelBLayout.setVerticalGroup(
            panelBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtPurchasePrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtSellingPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel13.setText("Movie:");

        jLabel10.setText("Actress #1:");

        jLabel8.setText("Actor #1:");

        jLabel11.setText("Actress #2:");

        jLabel12.setText("Director:");

        jLabel9.setText("Actor #2:");

        javax.swing.GroupLayout panelCLayout = new javax.swing.GroupLayout(panelC);
        panelC.setLayout(panelCLayout);
        panelCLayout.setHorizontalGroup(
            panelCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtActor1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtActor2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtActress1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtActress2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDirector, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelCLayout.setVerticalGroup(
            panelCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(txtActor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtActor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtActress1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtActress2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(txtDirector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel14.setText("Genre:");

        jLabel15.setText("Book");

        javax.swing.GroupLayout panelDLayout = new javax.swing.GroupLayout(panelD);
        panelD.setLayout(panelDLayout);
        panelDLayout.setHorizontalGroup(
            panelDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtGenre, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(panelDLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        panelDLayout.setVerticalGroup(
            panelDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtGenre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel17.setText("Width:");

        jLabel19.setText("Media:");

        jLabel16.setText("Painting:");

        jLabel18.setText("Height:");

        javax.swing.GroupLayout panelELayout = new javax.swing.GroupLayout(panelE);
        panelE.setLayout(panelELayout);
        panelELayout.setHorizontalGroup(
            panelELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelELayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelELayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtWidth, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMedia, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel16))
                .addContainerGap())
        );
        panelELayout.setVerticalGroup(
            panelELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelELayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtWidth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(txtHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(txtMedia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        txtOutput.setColumns(20);
        txtOutput.setRows(5);
        jScrollPane1.setViewportView(txtOutput);

        lblRecords.setText("Records:");

        jLabel21.setText("Data:");

        lblProfit.setText("Print");

        jLabel22.setText("Actions");

        btnAdd.setText("Add to Inventory");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnSell.setText("Sell Last Item");
        btnSell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSellActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelGLayout = new javax.swing.GroupLayout(panelG);
        panelG.setLayout(panelGLayout);
        panelGLayout.setHorizontalGroup(
            panelGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGLayout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelGLayout.createSequentialGroup()
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSell, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelGLayout.setVerticalGroup(
            panelGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnSell))
                .addContainerGap())
        );

        javax.swing.GroupLayout panelFLayout = new javax.swing.GroupLayout(panelF);
        panelF.setLayout(panelFLayout);
        panelFLayout.setHorizontalGroup(
            panelFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(lblRecords)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblProfit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelFLayout.createSequentialGroup()
                        .addGroup(panelFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(panelG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelFLayout.setVerticalGroup(
            panelFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblRecords)
                    .addComponent(lblProfit, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelG, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(panelA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(panelE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(panelD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // Placeholders for purchasePrice and SellingPrice values
        int buy = 0, sell = 0;
        // Placeholders width and height for painting
        int width = 0, height = 0;
        
        // Try-catch block
        try
        {
            // Tests for non-integer inputs
            buy = Integer.parseInt(txtPurchasePrice.getText());
            sell = Integer.parseInt(txtSellingPrice.getText());  
        } catch (NumberFormatException e)
        {
            JOptionPane.showMessageDialog(null, "Invalid input, Please enter Integers!", 
                    "Purchase or Selling Price Error", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "Invalid input, Please enter Integers!", 
                    "Purchase or Selling Price Error", JOptionPane.INFORMATION_MESSAGE);
        }
        
        // Try-catch block
        try 
        {
            // Tests date input is in the proper format
            date = new SimpleDateFormat("MM/dd/yy", Locale.ENGLISH).parse(txtDate.getText());
            
        } 
        catch (ParseException ex)
        {
            JOptionPane.showMessageDialog(null, "Invalid input, Enter valid date in this form: MM/DD/YY", 
                    "Date Error", JOptionPane.INFORMATION_MESSAGE);
        }
        catch (Exception ex)
        {
            JOptionPane.showMessageDialog(null, "Invalid input, Enter valid date in this form: MM/DD/YY", 
                    "Date Error", JOptionPane.INFORMATION_MESSAGE);
        }
        
        // If the radio button radBook is selected
        if(radBook.isSelected()){
            // If any of the textboxes in the book section are empty
            if(txtTitle.getText().isEmpty() || txtAuthor.getText().isEmpty() || txtDate.getText().isEmpty() ||
                    txtPurchasePrice.getText().isEmpty() || txtSellingPrice.getText().isEmpty() || txtGenre.getText().isEmpty()){
                // Show error message
                JOptionPane.showMessageDialog(null, "Empty Field(s)!");
                return;
            }
            // Store book into the inventory by passing to constructor
            Book bk = new Book(txtTitle.getText(), txtAuthor.getText(), date, buy, sell, txtGenre.getText());

            // Add new book to the arraylist
            itemInventory.add(bk);
            // Enable Sell button
            btnSell.setEnabled(true);
            
            // Display inventory in the output textArea
            txtOutput.setText("");
            printInventory();
        }
        
        // If the radio button radMovie is selected
        else if(radMovie.isSelected()){
            // If any of the textboxes in the movie section are empty
            if(txtTitle.getText().isEmpty() || txtAuthor.getText().isEmpty() || txtDate.getText().isEmpty() ||
                    txtPurchasePrice.getText().isEmpty() || txtSellingPrice.getText().isEmpty() || txtActor1.getText().isEmpty()
                    || txtActor2.getText().isEmpty() || txtActress1.getText().isEmpty() || txtActress2.getText().isEmpty()
                    || txtDirector.getText().isEmpty()){
                // Show error message
                JOptionPane.showMessageDialog(null, "Empty Field(s)!");
                return;
            }
            // Store movie into the inventory by passing to constructor
            Movie mv = new Movie(txtTitle.getText(), txtAuthor.getText(), date, buy, sell,
                                    txtActor1.getText(), txtActor2.getText(), txtActress1.getText(),
                                    txtActress2.getText(), txtDirector.getText());
            // Add movie to arraylist
            itemInventory.add(mv);
            // enable Sell button
            btnSell.setEnabled(true);
            
            // Display inventory in the output textArea
            txtOutput.setText("");
            printInventory();
        }
        
        // If the radio button radPainting is selected
        else if(radPainting.isSelected())
        {
            
            // Try-catch block
            try
            {
                // Check for invalid non-integer inputs for width and height fields
                width = Integer.parseInt(txtWidth.getText());
                height = Integer.parseInt(txtHeight.getText());  
                // catch parse error
            } catch (NumberFormatException e){
                JOptionPane.showMessageDialog(null, "Invalid input, Please enter Integers!", 
                        "Purchase or Selling Price Error", JOptionPane.INFORMATION_MESSAGE);
            }
            
            // If any of the textboxes in the movie section are empty
            if(txtTitle.getText().isEmpty() || txtAuthor.getText().isEmpty() || txtDate.getText().isEmpty() ||
                    txtPurchasePrice.getText().isEmpty() || txtSellingPrice.getText().isEmpty() | txtMedia.getText().isEmpty() 
                    || txtWidth.getText().isEmpty() ||  txtHeight.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Empty Field(s)!");
                return;
            }
            
            // Store Painting into the inventory by passing to constructor
            Painting pt = new Painting(txtTitle.getText(), txtAuthor.getText(), date, buy, sell,
                                    width, height, txtMedia.getText());
            // Add painting to the arraylist
            itemInventory.add(pt);
            // enable delete button
            btnSell.setEnabled(true);
            
            // Display inventory in the output textArea
            txtOutput.setText("");
            printInventory();
        }
        
        // Sets the following labels and panels to be enabled
        lblRecords.setEnabled(true);
        lblProfit.setEnabled(true);
        panelF.setEnabled(true);
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnSellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSellActionPerformed
        // Remove last item added in the form of a sale
        itemInventory.remove(itemInventory.size()-1);
        // Checks if its a movie/book/ painting and decrement their count
        try{
            if(itemInventory.get(itemInventory.size()-1) instanceof Book){
                ((Book)itemInventory.get(itemInventory.size()-1)).deleteBook();
            }
            else if(itemInventory.get(itemInventory.size()-1) instanceof Movie){
                ((Movie)itemInventory.get(itemInventory.size()-1)).deleteMovie();
            }
            else {
                ((Painting)itemInventory.get(itemInventory.size()-1)).deletePainting();
            }
            // Catch exception
        }catch (IndexOutOfBoundsException e){
            JOptionPane.showMessageDialog(null, "Inventory is Now Empty", 
                    "Invalid Index", JOptionPane.INFORMATION_MESSAGE);
            // Set all counts to zero if the arraylist is empty
            StoreItem.itemCount = 0;
            Book.bookCount = 0;
            Movie.movieCount = 0;
            Painting.paintingCount = 0;

            // Disable the delete button
            btnSell.setEnabled(false);
        }
        // Show the inventory in the output textArea
        txtOutput.setText("");
        printInventory();
        
        lblRecords.setEnabled(true);
        lblProfit.setEnabled(true);
        panelF.setEnabled(true);
    }//GEN-LAST:event_btnSellActionPerformed

    private void radBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radBookActionPerformed
        txtWidth.setEnabled(false);
        txtHeight.setEnabled(false);
        txtMedia.setEnabled(false);
        txtActor1.setEnabled(false);
        txtActor2.setEnabled(false);
        txtActress1.setEnabled(false);
        txtActress2.setEnabled(false);
        txtDirector.setEnabled(false);

        txtGenre.setEnabled(true);

        btnAdd.setEnabled(true);

        panelD.setEnabled(true);
        panelG.setEnabled(true);       
    }//GEN-LAST:event_radBookActionPerformed

    private void radMovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radMovieActionPerformed
        txtGenre.setEnabled(false);
        txtWidth.setEnabled(false);
        txtHeight.setEnabled(false);
        txtMedia.setEnabled(false);

        txtActor1.setEnabled(true);
        txtActor2.setEnabled(true);
        txtActress1.setEnabled(true);
        txtActress2.setEnabled(true);
        txtDirector.setEnabled(true);

        btnAdd.setEnabled(true);

        panelC.setEnabled(true);
        panelD.setEnabled(false);
        panelG.setEnabled(true);
    }//GEN-LAST:event_radMovieActionPerformed

    private void radPaintingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radPaintingActionPerformed
        txtActor1.setEnabled(false);
        txtActor2.setEnabled(false);
        txtActress1.setEnabled(false);
        txtActress2.setEnabled(false);
        txtGenre.setEnabled(false);
        txtDirector.setEnabled(false);

        txtWidth.setEnabled(true);
        txtHeight.setEnabled(true);
        txtMedia.setEnabled(true);

        btnAdd.setEnabled(true);

        panelC.setEnabled(false);
        panelD.setEnabled(false);
        panelG.setEnabled(true);
        panelE.setEnabled(true);
    }//GEN-LAST:event_radPaintingActionPerformed

    // Prints the values of the inventory into the text area while denoting what 
    // type of item and the format for printing
    private void printInventory(){
        // Integer placeholders for the profit of each type for book, movie, and painting
        int profitA = 0, profitB = 0, profitC = 0;
        // Integer placeholder counts for book, movie, and painting
        int countA = 0, countB = 0, countC = 0;
        // Integer placeholder for total items
        int totalItems = 0;
        // Integer placeholder for total profit.
        int total;
        
        // Iterate through the arraylist
        for(int i = 0; i < itemInventory.size(); i++){
            // Check if the position is a book
            if(itemInventory.get(i) instanceof Book){
                // Display book string
                txtOutput.append(((Book)itemInventory.get(i)).toString() + "\n");
                // Set profitA to the difference of the book methods
                profitA += itemInventory.get(i).getAskingPrice() - itemInventory.get(i).getPurchasePrice();
                // Set count a to the book count method
                countA = ((Book)itemInventory.get(i)).getBookCount();
            }
            
            // If the position is a movie
            else if(itemInventory.get(i) instanceof Movie){
                // Display movie strong
                txtOutput.append(((Movie)itemInventory.get(i)).toString()+ "\n");
                // Set profit to difference of askingPrice and PurchasePrice member methods
                profitB += itemInventory.get(i).getAskingPrice() - itemInventory.get(i).getPurchasePrice();
                // Set count b to the movieCount member method
                countB = ((Movie)itemInventory.get(i)).getMovieCount();
            }
            // If the position is a painting
            else if(itemInventory.get(i) instanceof Painting){
                // Display painting string
                txtOutput.append(((Painting)itemInventory.get(i)).toString() + "\n");
                // Set profit to difference of askingPrice and PurchasePrice member methods
                profitC += itemInventory.get(i).getAskingPrice() - itemInventory.get(i).getPurchasePrice();
                // Set countC to the member method value PaintingCount
                countC = ((Painting)itemInventory.get(i)).getPaintingCount();
            }
            // Set total items to the StoreItem itemCount
            totalItems = itemInventory.get(i).getCount();
        }
        
        // Set lblRecords to show the count of each item type
        lblRecords.setText("Books: " + countA  + "       Movies: " + countB + "       Paintings: " +
                         countC + "        Total Items: " + totalItems);
        // Calculate total profit with the other profit variables
        total = profitA + profitB + profitC;
        // Set lblProfit to display the total profit
        lblProfit.setText("Potential Profit: $ " + Integer.toString(total));
    }
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnSell;
    private javax.swing.ButtonGroup groupButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblProfit;
    private javax.swing.JLabel lblRecords;
    private javax.swing.JPanel panelA;
    private javax.swing.JPanel panelB;
    private javax.swing.JPanel panelC;
    private javax.swing.JPanel panelD;
    private javax.swing.JPanel panelE;
    private javax.swing.JPanel panelF;
    private javax.swing.JPanel panelG;
    private javax.swing.JRadioButton radBook;
    private javax.swing.JRadioButton radMovie;
    private javax.swing.JRadioButton radPainting;
    private javax.swing.JTextField txtActor1;
    private javax.swing.JTextField txtActor2;
    private javax.swing.JTextField txtActress1;
    private javax.swing.JTextField txtActress2;
    private javax.swing.JTextField txtAuthor;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtDirector;
    private javax.swing.JTextField txtGenre;
    private javax.swing.JTextField txtHeight;
    private javax.swing.JTextField txtMedia;
    private javax.swing.JTextArea txtOutput;
    private javax.swing.JTextField txtPurchasePrice;
    private javax.swing.JTextField txtSellingPrice;
    private javax.swing.JTextField txtTitle;
    private javax.swing.JTextField txtWidth;
    // End of variables declaration//GEN-END:variables

}
